// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_CLEAR = 'PRODUCT_CLEAR';

// LOCATIONS
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATION = 'GET_LOCATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';
export const LOCATIONS_CLEAR = 'LOCATIONS_CLEAR';

// PARTNERS
export const GET_PARTNERS = 'GET_PARTNERS';
export const GET_PARTNER = 'GET_PARTNER';
export const CREATE_PARTNER = 'CREATE_PARTNER';
export const UPDATE_PARTNER = 'UPDATE_PARTNER';
export const DELETE_PARTNER = 'DELETE_PARTNER';
export const PARTNERS_ERROR = 'PARTNERS_ERROR';

// CONTACTS
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACT = 'GET_CONTACT';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';
export const CONTACTS_CLEAR = 'CONTACTS_CLEAR';

// REVIEWS
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW = 'GET_REVIEW';
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const REVIEWS_ERROR = 'REVIEWS_ERROR';
export const REVIEWS_CLEAR = 'REVIEWS_CLEAR';

// PRODUCT HISTORY
export const GET_ALL_PRODUCTS_HISTORY = 'GET_ALL_PRODUCTS_HISTORY';
export const GET_SINGLE_PRODUCTS_HISTORY = 'GET_SINGLE_PRODUCTS_HISTORY';
export const GET_PRODUCTS_HISTORY_ERROR = 'GET_PRODUCTS_HISTORY_ERROR';
export const PRODUCTS_HISTORY_CLEAR = 'PRODUCTS_HISTORY_CLEAR';

// CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// CART
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const SET_CART = 'SET_CART';
export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';

// FAVORITES
export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITE = 'GET_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const CLEAR_FAVORITE = 'CLEAR_FAVORITE';
export const FAVORITES_ERROR = 'FAVORITES_ERROR';
